# Generated by Django 4.2.2 on 2023-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_rename_user_answer_author_rename_content_answer_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
    ]
